# Workflow Extension Template
# Template for creating project-specific workflow extensions

project_id: "{project-id}"
base_workflow: "{base-workflow-name}"
description: "{extension-description}"
extension_version: "1.0.0"
created_date: "{YYYY-MM-DD}"

# Phase-specific agent additions
supporting_agents_additions:
  {phase_name}:
    # High Priority Agents
    - {custom-agent-name-1}     # {agent-purpose-description}
    - {custom-agent-name-2}     # {agent-purpose-description}
    
    # Medium Priority Agents
    - {custom-agent-name-3}     # {agent-purpose-description}

# Project-specific MCP integration strategy
mcp_integration_strategy_additions:
  {integration_area_1}:
    focus: "{integration-focus-description}"
    targets: 
      - {target_metric_1}: "{target_value_1}"
      - {target_metric_2}: "{target_value_2}"
      
  {integration_area_2}:
    services:
      - {service_1}: "{service-purpose}"
      - {service_2}: "{service-purpose}"
    optimization_target: "{optimization-description}"

# Technology stack context for agent coordination
technology_context:
  {tech_category_1}: "{technology-stack-info}"
  {tech_category_2}: "{technology-stack-info}"
  {tech_category_3}: "{technology-stack-info}"
  
# Task integration phases (if applicable)
task_integration:
  phase_mapping:
    {phase_range_1}: "{phase-description}"
    {phase_range_2}: "{phase-description}"
  
  estimated_benefits:
    time_savings: "{hours-saved} hours ({percentage}% improvement)"
    {benefit_metric_1}: "{benefit-description}"
    {benefit_metric_2}: "{benefit-description}"

# Agent coordination strategy
agent_coordination:
  execution_order: "{priority_based|sequential|parallel}"
  context_sharing: "{enhanced|standard|minimal}"
  error_handling: "{cascade_resilient|independent|shared}"
  
# Metadata for workflow tracking
metadata:
  generated_by: "workflow-integrator"
  source_agents: [
    "{agent-file-1}.md",
    "{agent-file-2}.md",
    "{agent-file-3}.md"
  ]
  integration_date: "{YYYY-MM-DD}"
  total_agents_integrated: {number}
  estimated_complexity_reduction: "{percentage}%"

# Template Usage Instructions
# 1. Replace all {placeholder} values with project-specific values
# 2. Add actual custom agent names and their purposes
# 3. Define MCP integration strategy for the project
# 4. Set up technology context for proper agent coordination
# 5. Configure coordination strategy based on project needs