# Pull Request Workflow
# Automated pull request creation and merge management with human approval

name: pr-workflow
description: Complete pull request workflow from creation to merge with comprehensive validation and human approval
version: "1.0.0"

# Smart Context Schema
context_schema:
  pr_context:
    branch_name: string
    target_branch: string
    change_scope: object
    review_requirements: object
  merge_context:
    approval_status: object
    merge_strategy: string
    post_merge_tasks: array

# Workflow Definition
phases:
  # Phase 1: PR Analysis and Preparation
  - name: pr_analysis
    agent: pr-analyzer
    description: "Analyze code changes and assess impact for PR creation"
    inputs: []
    outputs:
      - change_analysis
      - impact_assessment
      - pr_metadata
    analysis_scope:
      - code_changes: comprehensive
      - dependency_impact: true
      - breaking_changes: detection
      - security_impact: assessment
    success_criteria:
      - changes_analyzed: true
      - impact_assessed: true
      - metadata_prepared: true
    next_phase: pr_content_generation

  # Phase 2: PR Content Generation
  - name: pr_content_generation
    agent: pr-generator
    description: "Generate high-quality PR content based on change analysis"
    inputs: [change_analysis, impact_assessment]
    outputs:
      - pr_title
      - pr_description
      - change_summary
      - test_plan
    content_elements:
      - title: descriptive_and_concise
      - description: comprehensive_with_context
      - change_summary: bullet_points
      - test_plan: verification_steps
    success_criteria:
      - content_generated: true
      - quality_standards_met: true
    next_phase: pr_validation

  # Phase 3: PR Quality Validation
  - name: pr_validation
    agent: pr-validator
    description: "Validate PR quality and readiness for review"
    inputs: [pr_content, change_analysis]
    outputs:
      - validation_results
      - quality_score
      - readiness_status
    validation_checks:
      - code_quality: linting_and_formatting
      - test_coverage: adequate_coverage
      - documentation: updated_if_needed
      - breaking_changes: properly_documented
      - security: no_vulnerabilities
    success_criteria:
      - quality_score: ">= 8.0"
      - all_checks_pass: true
      - no_blocking_issues: true
    next_phase: pr_creation

  # Phase 4: PR Creation
  - name: pr_creation
    agent: pr-create
    description: "Create pull request with generated content and metadata"
    inputs: [pr_content, validation_results]
    outputs:
      - pr_number
      - pr_url
      - creation_status
    creation_options:
      - auto_assign_reviewers: true
      - apply_labels: true
      - link_issues: true
      - draft_mode: conditional
    success_criteria:
      - pr_created_successfully: true
      - reviewers_assigned: true
      - metadata_applied: true
    next_phase: merge_preparation

  # Phase 5: Merge Preparation and Approval
  - name: merge_preparation
    agent: merge-approver
    description: "Prepare for merge and facilitate human approval process"
    inputs: [pr_details, validation_results]
    outputs:
      - merge_readiness_report
      - approval_request
      - pre_merge_checklist
    approval_requirements:
      - human_approval: mandatory
      - ci_checks_pass: required
      - code_review_complete: required
      - no_merge_conflicts: required
    success_criteria:
      - merge_ready: true
      - approvals_obtained: true
      - checks_passed: true
    approval_required: true
    on_approval:
      action: proceed_to_merge
    on_rejection:
      action: request_changes
    next_phase: pr_merge

  # Phase 6: PR Merge Execution
  - name: pr_merge
    agent: merge-executor
    description: "Execute safe pull request merge with validation"
    inputs: [merge_readiness_report, approval_status]
    outputs:
      - merge_result
      - merge_commit_sha
      - integration_status
    merge_strategies:
      - squash: default
      - merge_commit: for_feature_branches
      - rebase: for_clean_history
    safety_checks:
      - final_ci_validation: true
      - merge_conflict_detection: true
      - rollback_plan: prepared
    success_criteria:
      - merge_successful: true
      - no_integration_issues: true
      - rollback_plan_ready: true
    next_phase: post_merge_activities

  # Phase 7: Post-Merge Activities
  - name: post_merge_activities
    agent: post-merge-manager
    description: "Handle post-merge cleanup and notifications"
    inputs: [merge_result, pr_metadata]
    outputs:
      - cleanup_status
      - notification_status
      - next_actions
    activities:
      - branch_cleanup: delete_merged_branch
      - notifications: stakeholder_update
      - documentation: update_changelog
      - issue_closure: auto_close_linked_issues
      - deployment: trigger_if_configured
    success_criteria:
      - cleanup_completed: true
      - notifications_sent: true
      - documentation_updated: true
    next_phase: human_approval_pr

  # Phase 8: Human Approval Checkpoint
  - name: human_approval_pr
    type: human_interaction
    description: "Human review and approval of PR workflow completion before proceeding to acceptance phase"
    approval_scope:
      - "Pull request quality and merge execution validation"
      - "Code review completeness and approval adequacy"
      - "CI/CD pipeline success and integration testing results"
      - "Post-merge activities completion and branch cleanup"
      - "Documentation updates and changelog accuracy"
    review_materials:
      - pr_url
      - merge_result
      - cleanup_status
      - change_analysis
      - validation_results
      - post_merge_status
    decision_options: [approved, approved_with_conditions, rejected, deferred]
    stakeholders:
      required: [technical_lead]
      optional: [product_owner, release_manager]
    timeout: 24 # hours
    on_approval: 
      next_workflow: acceptance
    on_rejection:
      rollback_to_phase: pr_analysis
      feedback_collection: true

# Conditional Workflow Branches
conditional_branches:
  draft_pr:
    condition: "context.draft_mode === true"
    skip_phases: [merge_preparation, pr_merge]
    alternative_flow: [review_iteration]
  
  hotfix_pr:
    condition: "context.pr_type === 'hotfix'"
    expedited_approval: true
    merge_strategy: "squash"
    post_merge_activities: [immediate_deployment]

# Parallel Execution Support
parallel_groups:
  validation_checks:
    condition: "context.comprehensive_validation === true"
    phases: [pr_validation]
    sub_processes:
      - code_quality_check: parallel
      - security_scan: parallel
      - test_validation: parallel
      - documentation_check: parallel

# Human Interaction Points
human_interactions:
  code_review:
    phase: merge_preparation
    type: required
    timeout: 48h
    escalation: notify_leads
  
  merge_approval:
    phase: merge_preparation
    type: mandatory
    approval_criteria:
      - code_review_approved: true
      - ci_checks_pass: true
      - no_merge_conflicts: true
  
  emergency_merge:
    condition: "context.emergency === true"
    approval_level: senior_engineer
    bypass_normal_checks: conditional

# Error Handling and Recovery
error_handling:
  retry_policy:
    max_retries: 2
    retry_delay: 60s
  
  recovery_strategies:
    pr_creation_failure:
      action: retry_with_adjusted_content
      fallback: manual_pr_creation
    
    merge_conflict:
      action: notify_author
      provide: conflict_resolution_guidance
    
    ci_failure:
      action: block_merge
      notify: author_and_reviewers
    
    merge_failure:
      action: rollback_preparation
      escalate: true

# Quality Gates
quality_gates:
  pr_quality:
    title_quality: descriptive
    description_completeness: comprehensive
    change_documentation: adequate
  
  code_quality:
    linting_pass: required
    test_coverage: ">= 80%"
    no_security_vulnerabilities: required
  
  review_quality:
    reviewer_approval: required
    change_discussion: adequate
    concerns_resolved: true

# Integration Points
integrations:
  ci_cd:
    trigger_builds: automatic
    status_checks: required
    deployment: conditional
  
  project_management:
    link_issues: automatic
    update_status: on_merge
    close_completed: true
  
  notifications:
    slack: team_channels
    email: stakeholders
    dashboard: project_status

# Monitoring and Analytics
monitoring:
  metrics:
    - pr_creation_time
    - review_cycle_time
    - merge_success_rate
    - quality_gate_pass_rate
    - post_merge_issues
  
  alerts:
    - merge_conflicts: immediate
    - ci_failures: 5_minutes
    - approval_delays: 24_hours
    - quality_gate_failures: immediate
  
  notifications:
    - pr_created
    - review_requested
    - approval_granted
    - merge_completed
    - issues_detected

# Workflow Customization
customization:
  by_repository:
    quality_gates: configurable
    approval_requirements: adjustable
    merge_strategies: selectable
  
  by_branch_type:
    main: strict_requirements
    develop: standard_requirements
    feature: flexible_requirements
    hotfix: expedited_process